version: '3'

networks:
  backend:

services:

  ape:
    build: .
    command: ["flask", "run", "--host=0.0.0.0"]
    # command: ["pytest", "--color=yes", "-s", "http_wrapper/tests.py"]
    environment:
      - FLASK_ENV=development
      - EMBEDDING_PATH=nk_ape/embeddings/GoogleNews-vectors-negative300.bin.gz
      # - EMBEDDING_PATH=nk_ape/embeddings/lexvec.enwiki+newscrawl.300d.W.pos.vectors
    # env_file:
    #   - ape.env
    networks:
      - backend
    ports:
      - 5000:5000
    volumes:
      - .:/app
      - ./nk_ape/embeddings/wiki2vec:/app/nk_ape/embeddings/wiki2vec

